require(deSolve)
require(ggplot2)
require(cowplot)
############################
# Influenza-Like Illness General Model 
# Julie A. Spencer and Helen J. Wearing
# This code will solve SEIR a system of ODEs aimed at modeling the outbreak curve of 
# five common upper respiratory viruses within a contained population.
# 
# The output of this code is 
# (1) an epidemic curve to show timing and magnitude of the epidemic peak for each virus
# (2) cumulative infections for each virus
# (3) global sensitivity plots for each virus
# Note 1: to generate the epidemic curves, parameters from Table 3 should
# be inserted for each virus.
# Note 2: for the global sensitivity analysis, mean parameters from Table 3
# should be inserted in the script titled ILI_LHC_sample;
# the samples generated will override the hard-coded sample parameters herein.
############################

# starting with basic SEIR model from Keeling & Rohani (2008) textbook.

# assumptions: 
# (1) from initial infection, individuals progress to (a) hospital, (b) recovery
# (2) from the hospital, individuals progress to (a) death, (b) recovery
# (3) everyone who recovers gains full immunity
# (4) total infectious population = I + H
# (5) no coinfection is assumed
# (6) homogeneous mixing

# Set up a time vector
time = seq(0, 365, by=.1) # in days

############################################### PARAMETERS BEGIN ###############################
# Set parameter values
beta = .0001 #  basic transmission rate dimless  (citation) 
c = 1 # transmission reduction in hospital (lit citation)
gamma1= 1/1 # rate of progression through exposed class (1/days)
gamma2 = 1/4 # rate of progression through first infectious class (1/days)
gamma3 = 1/2 # rate of progression through hospitalized class (1/days)
gamma4 = 1/2 # rate of progression through non-hospitalized infectious state(1/days)
p1 = 0.1 # proportion of infectious class that are hospitalized
p2 = 0.05 # proportion of hospitalized class that die

#Vector of hard coded or inputed parameter values
params = c(beta, c, gamma1, gamma2, gamma3, gamma4, p1, p2)

# Read in matrix of parameter sets generated by LHS
# You need to source ILI_LHS_sample.R the first time you use this code
# At the moment this includes 5 parameter values: beta, gamma1, gamma2, gamma3, gamma4
lhs_params = read.csv(file = "LHS_samples.csv")
nsamples = nrow(lhs_params)
############################################ PARAMETERS END ############################################

############################################ INITIAL CONDITIONS BEGIN ##################################
# Set initial values for state variables
# Note: vaccination is not included in this model.
vacc = 0
vacc.effect = 0
S = 9999 
SV = S*vacc*vacc.effect
Sinit = ceiling(S - SV)
Einit = 0
I_1init = 1
I_2init = 0
Hinit = 0
Rinit = 0
Dinit = 0
ITinit = 0

xstart = c(S = Sinit, E = Einit, I_1 = I_1init, I_2 = I_2init, H = Hinit, R = Rinit, D = Dinit, IT=ITinit)
############################################ INITIAL CONDITIONS END ####################################

############################################ SEIR ODE SYSTEM SET UP BEGIN ##############################
# Function that evaluates the SEIR model
 ILI_model <- function (t, x, params) {
  # Extract the state variables
  S = x['S'] # susceptible state
  E = x['E'] # exposed, not infectious state
  I_1 = x['I_1'] # initially infectious state
  I_2 = x['I_2'] # non-hospitalized infectious state
  H = x['H'] # hospitalized state
  R = x['R'] # recovered state
  D = x['D'] # dead state
  IT = x['IT'] # total cumulative infected
 
  N = S + E + I_1 + I_2 + H + R + D
  
  # Extract the parameter values
  beta = params[1]
  c = params[2]
  gamma1 = params[3]
  gamma2 = params[4]
  gamma3 = params[5]
  gamma4 = params[6]
  p1 = params[7]
  p2 = params[8]
  
  # Evaluate the ordinary differential equations at time t
  dSdt = -beta*S*(I_1+I_2+c*H) # transmission by all infected classes
  dEdt = beta*S*(I_1+I_2+c*H) - gamma1*E
  dI_1dt = gamma1*E - gamma2*I_1
  dI_2dt = gamma2*(1-p1)*I_1 - gamma4*I_2
  dHdt = gamma2*p1*I_1 - gamma3*H
  dRdt = gamma4*I_2 + gamma3*(1-p2)*H
  dDdt = gamma3*p2*H
  dITdt = beta*S*(I_1+I_2+c*H)
  
  # Combine into a single vector
  dxdt = c(dSdt, dEdt, dI_1dt, dI_2dt, dHdt, dRdt, dDdt, dITdt)
  
  # Return as a list (required by ODE solver)
  return(list(dxdt))
}
############################################ SEIR ODE SYSTEM SET UP END #############################

############################### PARAMETER SWEEP ####################################################################
totalinfections = vector('numeric',nsamples)
peak_height = vector('numeric',nsamples)
time_to_peak = vector('numeric',nsamples)

for (i in 1:nsamples){
  params = c(beta=lhs_params[i,1], c=c, gamma1=lhs_params[i,2], 
             gamma2=lhs_params[i,3], gamma3=lhs_params[i,4], gamma4=lhs_params[i,5], p1=p1, p2=p2)
  solns = as.data.frame(ode(xstart,time,ILI_model,params))
  # Extracting total (cumulative) infections
  totalinfections[i] = tail(solns$IT,n=1)
  # Extracting all infectious classes
  Iclasses = solns$I_1+solns$I_2+solns$H
  # Finding peak height (max) of infectious classes
  peak_height[i] = max(Iclasses)
  # Finding time to peak
  indexpeak = which.max(Iclasses)
  time_to_peak[i] = solns$time[indexpeak]
}

############################### PARAMETER SWEEP ENDS HERE ##########################################

############################ PLOTS #####################################
# Distributions
par(mfrow=c(1,1))
hist(totalinfections,xlab='total infections',main='')
hist(peak_height,xlab='peak height',main='')
hist(time_to_peak,xlab='time to peak',main='')

# Marginal relations between individual parameters and output
par(mfrow=c(2,3))
plot(lhs_params[,1],totalinfections,type='p', xlab='beta', ylab='total infections')
plot(lhs_params[,2],totalinfections,type='p', xlab='gamma1',ylab='')
plot(lhs_params[,3],totalinfections,type='p', xlab='gamma2',ylab='')
plot(lhs_params[,4],totalinfections,type='p', xlab='gamma3',ylab='total infections')
plot(lhs_params[,5],totalinfections,type='p', xlab='gamma4',ylab='')

par(mfrow=c(2,3))
plot(lhs_params[,1],peak_height,type='p', xlab='beta', ylab='peak height')
plot(lhs_params[,2],peak_height,type='p', xlab='gamma1',ylab='')
plot(lhs_params[,3],peak_height,type='p', xlab='gamma2',ylab='')
plot(lhs_params[,4],peak_height,type='p', xlab='gamma3',ylab='peak height')
plot(lhs_params[,5],peak_height,type='p', xlab='gamma4',ylab='')

par(mfrow=c(2,3))
plot(lhs_params[,1],time_to_peak,type='p', xlab='beta', ylab='time to peak')
plot(lhs_params[,2],time_to_peak,type='p', xlab='gamma1',ylab='')
plot(lhs_params[,3],time_to_peak,type='p', xlab='gamma2',ylab='')
plot(lhs_params[,4],time_to_peak,type='p', xlab='gamma3',ylab='time to peak')
plot(lhs_params[,5],time_to_peak,type='p', xlab='gamma4',ylab='')


# Gather data in dataframe

df.lhs <- data.frame(beta=lhs_params[,1],gamma1=lhs_params[,2],
                     gamma2=lhs_params[,3],gamma3=lhs_params[,4],
                     gamma4=lhs_params[,5],
                     totalinfections,peak_height,time_to_peak)

# Generate plots with points and smoothed local regression curve (these
#are for total infections output)

# Note: sometimes I need to re-run these individually because
#stat_smooth gets stuck

p1 <- ggplot(df.lhs, aes(x = beta, y = totalinfections)) +
  geom_point(alpha=0.5) +
  stat_smooth(method = "loess", formula = y ~ x, size = 1) +
  labs(x = expression(beta), y="Total Infections")
p2 <- ggplot(df.lhs, aes(x = gamma1, y = totalinfections)) +
  geom_point(alpha=0.5) +
  stat_smooth(method = "loess", formula = y ~ x, size = 1) +
  labs(x = expression(gamma[1]), y="Total Infections")
p3 <- ggplot(df.lhs, aes(x = gamma2, y = totalinfections)) +
  geom_point(alpha=0.5) +
  stat_smooth(method = "loess", formula = y ~ x, size = 1) +
  labs(x = expression(gamma[2]), y="Total Infections")
p4 <- ggplot(df.lhs, aes(x = gamma3, y = totalinfections)) +
  geom_point(alpha=0.5) +
  stat_smooth(method = "loess", formula = y ~ x, size = 1) +
  labs(x = expression(gamma[3]), y="Total Infections")
p5 <- ggplot(df.lhs, aes(x = gamma4, y = totalinfections)) +
  geom_point(alpha=0.5) +
  stat_smooth(method = "loess", formula = y ~ x, size = 1) +
  labs(x = expression(gamma[4]), y="Total Infections")

# Arrange plots in multi-panel figure

plot_grid(p1, p2, p3, p4, p5, labels = c("A", "B", "C", "D", "E"), ncol
          = 3, nrow = 2)

